name: Run Playwright in Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t playwright-tests

      - name: Run Playwright tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
            -e BASE_URL=https://guest:welcome2qauto@qauto.forstudy.space \
            -e LOGIN=testinho@meta.ua \
            -e PASSWORD=Test123! \
            playwright-tests
