name: Playwright Tests
on:
  push:
    branches: [ apiPlaywright ]
  pull_request:
    branches: [ apiPlaywright ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test
